title: Truckee Labs
subtitle: Lake Tahoe, California
desctiption: Truckee Labs, Lake Tahoe, California
url: http://www.speal.ca/truckee-labs
permalink: ':title/'

markdown: kramdown
# baseurl: "/truckee-labs" # not sure why I'd want this..

sass:
    style: compressed

# TODO reference these programatically. For now they need to be copypasted into each post
colors:
  red: BF360C # people
  blue: 054ec4 # projects
  orange: FF6F00 #events

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge

# Tracker
analytics: 

# Comments
disqus-shortname: truckee-labs

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
version: 0.8

gems: [jekyll-paginate, jekyll-seo-tag]